### ISSUE TITLE
General Project Questions

### ISSUE THREAD

**Issue by one000mph** [andyet/teleport#1]
1. **VM/Network Resources** I'd like to set up testing clusters with GCP & AWS VMs. So far I've used some bare metal servers that we already had online. We have GCP & AWS accounts for our own services, but for billing purposes we'll need to keep these VMs and networking resources separate. How would you like to handle this? Unfortunately I think I've already used my personal emails to sign up for trial accounts. It's possible that I could create a new temp email for this project, but I might need to input billing information regardless. I'll try to keep the resource usage for this project as minimal as possible.
2. **Diagrams** There are already some nice diagrams throughout the docs. Later on I'd like to create a few more and/or move them around. Is it possible to get access to the image assets that were used to create these?

**Comment by benarent** [comment]
For 1. , I would recommend that you create https://aws.amazon.com/organizations/  for AWS  ( which I've used before that works well ) and GCP has https://cloud.google.com/resource-manager/docs/creating-managing-organization but I've not use it. 

For 2. We've some of these in lucid charts, https://www.lucidchart.com/documents/edit/75a60dcc-4599-456c-a6fa-1637ba936ad5/0_0 I'll invite you to them.

**Comment by one000mph** [comment]
Thanks! I sent an email about cloud resource organizing and billing. Got the lucid charts as well.
